### ISSUE TITLE
runner.asm via emscriptem/wasm.sh has `tempDoublePointer` metadata type error

### ISSUE THREAD

**Issue by egberts** [samthor/prsr#1]
Ran `bash -x wasm/wsm.sh` and got a flurry of outputs:

```bash
$ bash -x wasm/wasm.sh
+ set -eu
+ FLAGS='-O1 -g4'
+ export EMCC_DEBUG=1
+ EMCC_DEBUG=1
+ [[ '' == \r\e\l\e\a\s\e ]]
+ [[ '' != '' ]]
+ MEMORY=131072
+ STACK=32000
+ emcc -O1 -g4 -s EMIT_EMSCRIPTEN_METADATA=1 \
    -s SIDE_MODULE=1 -s TOTAL_MEMORY=131072 \
    -s TOTAL_STACK=32000 -o runner.wasm \
    runner.c stdlib.c ../helper.c ../parser.c ../token.c 
shared:DEBUG: ^[[35mEM_CONFIG is located in /Users/egbert/.emscripten^[[0m
shared:DEBUG: ^[[35mTEMP_DIR not defined in /Users/egbert/.emscripten, using /tmp^[[0m
shared:DEBUG: ^[[35mPYTHON not defined in /Users/egbert/.emscripten, using "/usr/local/opt/python/bin/python3.7"^[[0m 

<snipped for brevity>
...
emcc:DEBUG: emcc step "asm2wasm" took 0.13 seconds
shared:DEBUG: creating wasm dynamic library with mem size 32224, table size 2, align 4
cache:DEBUG: PID 85507 released multiprocess file lock to Emscripten cache at /Users/egbert/.emscripten_cache/asmjs
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/1.38.32/libexec/emcc.py", line 3338, in <module>
    sys.exit(run(sys.argv))
  File "/usr/local/Cellar/emscripten/1.38.32/libexec/emcc.py", line 2230, in run
    optimizer)
  File "/usr/local/Cellar/emscripten/1.38.32/libexec/emcc.py", line 2749, in do_binaryen
    shared.WebAssembly.add_emscripten_metadata(final, wasm_binary_target)
  File "/usr/local/Cellar/emscripten/1.38.32/libexec/tools/shared.py", line 3052, in add_emscripten_metadata
    tempdouble_ptr = int(m.group(2))
AttributeError: 'NoneType' object has no attribute 'group'
bash-3.2$ exit
```

Error is located in `emscripten` shared.py tool:

```python
  @staticmethod
  def add_emscripten_metadata(js_file, wasm_file):
    WASM_PAGE_SIZE = 65536

    mem_size = Settings.TOTAL_MEMORY // WASM_PAGE_SIZE
    table_size = Settings.WASM_TABLE_SIZE
    global_base = Settings.GLOBAL_BASE

    js = open(js_file).read()
    m = re.search(r"(^|\s)tempDoublePtr\s+=\s+(\d+)", js)  #  BLOWS UP HERE
    tempdouble_ptr = int(m.group(2))
    m = re.search(r"(^|\s)DYNAMIC_BASE\s+=\s+(\d+)", js)
    dynamic_base = int(m.group(2))
    m = re.search(r"(^|\s)DYNAMICTOP_PTR\s+=\s+(\d+)", js)
    dynamictop_ptr = int(m.group(2))

    logger.debug('creating wasm emscripten metadata section with mem size %d, table size %d' % (mem_size, table_size,)) 
    name = b'\x13emscripten_metadata' # section name, including prefixed size
    contents = (
      # metadata section version
      WebAssembly.lebify(EMSCRIPTEN_METADATA_MAJOR) +
```
Looks like it is trying to build the metadata but failed.

Emscripten 1.38.32
uname -a: Darwin macbook.home 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
Python 3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)]
MacOS 10.14.5

**Comment by egberts** [comment]
runner.wasm.map:

JSON-prettified:
```bash
$ json_pp < runner.wasm.map 
```
```json
{
   "names" : [],
   "version" : 3,
   "mappings" : "8XASA,oGAWA,oBAOA,gBACA,mBACA,OAQA,mCClCA,6BAQA,yDAIA,0CAKA,SAQA,YARA,OACA,qBAGA,OACA,OALA,eAQA,IAPA,gBACA,OAMA,OAIA,uBACA,oBAGA,OAJA,gBAOA,QC7BA,uFAEA,mCAEA,eAOA,eAyUA,IAhVA,OAEA,4CAGA,eA2UA,IA9UA,SACA,cA6UA,IAvUA,kEAGA,eAoUA,IAvUA,aACA,cAsUA,IAlVA,QAkBA,wFAGA,eA6TA,IAhUA,iBACA,cA+TA,IA3TA,+CAEA,gCAEA,mBAuTA,IApTA,eAoTA,IAlTA,4CAGA,eA+SA,IAlTA,SACA,cAiTA,IAzTA,QAcA,kEAGA,eAwSA,IA3SA,aACA,cA0SA,IAtSA,mBAsSA,IAtSA,OAGA,gCAEA,mBAiSA,IA9RA,eA8RA,IA5RA,wFAGA,eAyRA,IA5RA,iBACA,cA2RA,IAnSA,QAxBA,QAwCA,yCAEA,2CAEA,8GAGA,eA4QA,IA/QA,qBACA,cA8QA,IA1QA,wFAGA,eAuQA,IA1QA,iBACA,cAyQA,IArQA,kEAGA,eAkQA,IArQA,aACA,cAoQA,IAjRA,QAmBA,eA8PA,IAnRA,QAyBA,6CAEA,4CAGA,eAqPA,IAxPA,SACA,cAuPA,IAnPA,4CAGA,eAgPA,IAnPA,SACA,cAkPA,IA9OA,mCAEA,kEAGA,eAyOA,IA5OA,aACA,cA2OA,IAvOA,wFAGA,eAoOA,IAvOA,iBACA,cAsOA,IA9OA,QAZA,QA4BA,yDAEA,kEAGA,eAyNA,IA5NA,aACA,cA2NA,IAvNA,8GAGA,eAoNA,IAvNA,qBACA,cAsNA,IAlNA,mBAkNA,IA/MA,eA+MA,IA7MA,4CAGA,eA0MA,IA7MA,SACA,cA4MA,IAxMA,oIAGA,eAqMA,IAxMA,yBACA,cAuMA,IA9NA,QA6BA,4CAGA,eA8LA,IAjMA,SACA,cAgMA,IA5LA,yCAEA,eA0LA,IAxLA,mBAwLA,IAxLA,OAGA,kCAEA,oIAGA,eAgLA,IAnLA,yBACA,cAkLA,IA9KA,4CAGA,eA2KA,IA9KA,SACA,cA6KA,IArLA,QAcA,gCAEA,0JAGA,eAkKA,IArKA,6BACA,cAoKA,IAhKA,oIAGA,eA6JA,IAhKA,yBACA,cA+JA,IA3JA,eA2JA,IA5LA,QAqCA,4CAGA,eAoJA,IAvJA,SACA,cAsJA,IAlJA,+CAEA,mBAgJA,IA7IA,eA6IA,IA3IA,4CAGA,eAwIA,IA3IA,SACA,cA0IA,IAlJA,QAcA,mBAoIA,IAjIA,eAiIA,IA/HA,qDAEA,8GAGA,eA0HA,IA7HA,qBACA,cA4HA,IAxHA,qCAEA,wFAGA,eAmHA,IAtHA,iBACA,cAqHA,IAjHA,oIAGA,eA8GA,IAjHA,yBACA,cAgHA,IAxHA,QAcA,wFAGA,eAuGA,IA1GA,iBACA,cAyGA,IA/HA,QA4BA,8GAGA,eAgGA,IAnGA,qBACA,cAkGA,IA9FA,qDAEA,mBA4FA,IAzFA,eAyFA,IAvFA,wFAGA,eAoFA,IAvFA,iBACA,cAsFA,IAlFA,kEAGA,eA+EA,IAlFA,aACA,cAiFA,IA7EA,wFAGA,eA0EA,IA7EA,iBACA,cA4EA,IA9FA,QAwBA,kDAEA,wCAEA,mBAkEA,IA/DA,eA+DA,IA7DA,4CAGA,eA0DA,IA7DA,SACA,cA4DA,IApEA,QAcA,mCAEA,mBAoDA,IAjDA,eAiDA,IA/CA,eA+CA,IAtDA,QAWA,wFAGA,eAwCA,IA3CA,iBACA,cA0CA,IAtEA,QAkCA,6CAEA,mBAkCA,IA/BA,eA+BA,IA7BA,4CAGA,eA0BA,IA7BA,SACA,cA4BA,IApCA,QAcA,gCAEA,kEAGA,eAiBA,IApBA,aACA,cAmBA,IAfA,4CAGA,eAYA,IAfA,SACA,cAcA,IAtBA,QAcA,wFAGA,eAKA,IARA,iBACA,cAOA,IApVA,4BCyyCA,UACA,qBACA,cACA,IACA,qCAEA,OACA,qBACA,cACA,cAEA,0CACA,OACA,0CAIA,8CACA,OACA,MACA,IAKA,cACA,eAOA,cACA,2BADA,KAhBA,0BA6DA,KAzBA,kBACA,IADA,SAGA,KAEA,qBACA,OALA,kBAUA,OAEA,cAWA,aACA,OAzwCA,qEACA,gBAmlBA,+DAGA,yCAQA,sDACA,OACA,MACA,yBA6jBA,IAtjBA,2EACA,UAXA,IAgkBA,IAhjBA,OACA,mCACA,kBACA,wCAxBA,kBAqkBA,IAxiBA,6CAwiBA,IAjiBA,UAiiBA,IA7hBA,cAEA,qEAEA,qBACA,OACA,UAuhBA,IAhhBA,OACA,MACA,uCA8gBA,IA1gBA,4BAMA,4BACA,4BACA,2BAyDA,qDACA,qBACA,QAucA,KAlcA,qBACA,QAicA,IA5fA,gCA4fA,IAxfA,OACA,qBAEA,gCAqfA,IArfA,GAyBA,kCACA,qBACA,QA0dA,IA5dA,WAIA,QAwdA,MAldA,4BAKA,QA6cA,IAldA,OAEA,WAgdA,MAjfA,qBAEA,yBAEA,4BACA,QAEA,qBAEA,WACA,QAGA,qBACA,WAmeA,IAleA,kBAkeA,IAjeA,UAieA,IAxbA,mCACA,yBACA,mCACA,SAIA,sCACA,yBACA,mCACA,UAFA,MAOA,yBACA,OACA,QAIA,qCACA,wCACA,mCACA,SAIA,iEAGA,0EAeA,OACA,UAyYA,IApYA,qBAEA,qCAkYA,IA9XA,kBACA,QA6XA,IA/YA,MACA,gEA8YA,IArXA,UAqXA,IA/WA,6DAGA,OACA,MACA,qBAGA,4DAuWA,IAlWA,6BAGA,QA+VA,IAlWA,GASA,+FAKA,QAoVA,IA/UA,OACA,MACA,yBA6UA,IAxUA,OACA,cACA,qBACA,OACA,MACA,0CACA,8CAkUA,IA3TA,kBA2TA,IAtTA,mDAEA,mCACA,OACA,MACA,6BAiTA,KA7SA,0CA6SA,IA1SA,qBACA,OACA,UAwSA,IA3RA,4BACA,mBADA,EA2CA,wDAIA,OACA,eAEA,gBAPA,AAqBA,OAEA,qBACA,OACA,UAuNA,IApNA,MACA,UAmNA,OA3RA,cAIA,YAJA,UAOA,gCAWA,kCATA,mFATA,QAyBA,qBASA,8CAEA,gBApCA,KAUA,mCACA,OACA,OACA,MACA,yBA6QA,IAvQA,kBAuQA,IA3RA,IA6EA,MA8MA,IAnMA,uBAmMA,IA5LA,wBAIA,+BAIA,qBACA,OACA,UAkLA,IA9KA,qBAIA,eAUA,4CAgKA,IAlHA,6FACA,qBACA,OACA,WA+GA,KA1GA,iBA0GA,IAtGA,8EAIA,4BACA,OACA,SAgGA,KAtGA,GAWA,WACA,4BACA,WAGA,cAsFA,KAlFA,MACA,6BAiFA,IA5EA,+DAIA,4BACA,OACA,MACA,6BAqEA,IA5EA,WAaA,4BACA,OAEA,uCAMA,eAsDA,IArDA,qBACA,WAoDA,KA3DA,MACA,6BA0DA,MAxCA,aACA,MACA,yBAsCA,IAjCA,aAyBA,eAQA,IAhCA,MACA,qBAEA,4BACA,OAGA,6BAEA,4BACA,SAIA,iBAkBA,KAlBA,yBAkBA,IAjBA,OACA,MACA,yBAeA,IAvJA,mCAKA,0CAGA,mCAIA,yBAIA,OACA,YAIA,aAKA,UAEA,+BAyHA,UAEA,IA3kBA,QArmBA,kBACA,4BACA,sCAKA,OADA,iBACA,IAKA,IANA,kBACA,wBAGA,uBAJA,iBACA,WAKA,QApEA,sEACA,OACA,iDACA,oEAuFA,cACA,kCADA,MAoPA,mCACA,KAIA,qDAIA,mCACA,OACA,MACA,2CAIA,oCAEA,gEAtVA,wCACA,OAEA,4BACA,kDAEA,0CA2FA,QAIA,gCAWA,GAfA,qBASA,uBAKA,YALA,wBALA,6CAzFA,OAEA,4BACA,mCAEA,+CAmRA,kDAGA,UAHA,cAOA,WAPA,yBAUA,4BAVA,cAaA,aAbA,QAiBA,QAyCA,mCAEA,8EAEA,mCACA,QAIA,WAoQA,IA3QA,IAWA,qBAIA,UA4PA,IA9PA,QA8PA,IAzPA,gCAyPA,IA3QA,AA8DA,0BAEA,mCACA,OADA,QAGA,kBAwMA,IAzMA,4BACA,uBAwMA,IAtMA,UAsMA,KAlMA,uCAEA,kBAgMA,IA7LA,qBACA,OACA,UA2LA,MApLA,OACA,MACA,uCAkLA,IA9KA,0BACA,qBACA,QA4KA,IAzIA,oCAGA,4BAKA,6CALA,OACA,WAqIA,IAzIA,WAmBA,oBACA,mCAGA,QAkHA,IA7GA,4BACA,SAIA,QAwGA,MA7HA,QA6HA,IArGA,mCACA,QAIA,QAgGA,IA3QA,QAyBA,cAEA,uCAGA,SA6OA,IA5OA,UA4OA,IArOA,WAqOA,IAhPA,OA+BA,gBAiNA,IAhOA,uBAgOA,IA9NA,WA8NA,IA3QA,AAqGA,OAGA,QAmKA,KA5JA,mCACA,4DAGA,OACA,UAuJA,KAnJA,gBACA,mBAIA,wBAsDA,cAwFA,IApFA,OAGA,mDACA,4BACA,OAEA,oCA6EA,IA3EA,SA2EA,IAjFA,AAaA,mCAEA,4BACA,QAiEA,KA5DA,uDAEA,KACA,iBAyDA,IAtDA,iDAEA,4BACA,QAmDA,QA9CA,mDACA,sEAEA,cACA,UA0CA,KAtCA,4BACA,QAqCA,IA9CA,AAaA,WA6BA,qBACA,sBAEA,QACA,IA9CA,MAcA,cAEA,4BAOA,kEAEA,6BAMA,OACA,UAcA,IATA,4BACA,QAQA,KA5IA,QA4IA,QAKA,cAQA,kBAuBA,IAvBA,IAEA,oCAEA,oCAmBA,IAdA,sBAcA,IAPA,kBAOA,QAvaA,6DAGA,mCAeA,IAJA,kDAIA,IAlBA,mBAXA,gCAIA,IAJA,yBAIA,IADA,0BACA,IADA,kBACA,OA3IA,gCAMA,IADA,8BACA,IADA,aACA,QA2GA,gDAkBA,IAlBA,sBAIA,cACA,mCACA,OAEA,wEACA,4BACA,SAIA,cAIA,IAJA,yBAIA,IAHA,WAGA,QAjMA,4BAEA,qDAeA,KAVA,oCAUA,IARA,mCACA,QADA,IAQA,KAFA,UAEA,QAuOA,8BAeA,IAVA,0DACA,yDASA,MAFA,mCACA,QACA,QA5GA,MACA,OACA,MACA,+EAYA,IAPA,MACA,WAMA,IALA,UAKA,QAtEA,sCA0BA,IAzBA,2CAyBA,KA1BA,oBASA,8CACA,WACA,OACA,mCACA,QAEA,mCACA,OAGA,kBAEA,OADA,QAKA,QACA,QAIA,6BAoBA,IAjBA,mCACA,OAGA,OACA,eAYA,IAZA,yBAYA,IAVA,yHAQA,WAEA,OAzGA,wCAEA,gCAFA,cAOA,OA0CA,4CAyIA,eAGA,iEASA,QC0MA,iEAEA,UAEA,oCACA,qBACA,WA2DA,IAtDA,OACA,qBACA,iBAEA,KACA,UAiDA,MA5CA,uDAGA,0DAGA,uCAsCA,IApCA,gBACA,cACA,KAEA,cACA,UAEA,iBAQA,0CAIA,sEAHA,QAoBA,IAbA,sCAIA,oEACA,OACA,oDALA,QAYA,KAFA,QAEA,OAtKA,0FA7CA,uCAEA,2CAEA,gBAJA,AAYA,kCAZA,WAuBA,oBAIA,WAEA,QACA,KAzXA,qBACA,SAGA,yCAOA,OAEA,iIA0BA,QA1BA,yBASA,OACA,mBAKA,qCA8YA,mCAGA,0CAgBA,eACA,cACA,qBAGA,wBACA,cACA,qBACA,MACA,OACA,QACA,UAHA,MAOA,QACA,gEACA,4BACA,qBACA,OACA,2CAKA,UAKA,OACA,iBACA,WACA,6BADA,GAQA,8DACA,iBArBA,IAyBA,EA3DA,mCACA,OACA,iBAEA,OACA,mCACA,wBACA,2CAEA,iBAzYA,WAGA,eAGA,YAIA,qBACA,uKAUA,8BAVA,GAiBA,qBACA,OACA,sBAFA,GAjBA,KA2BA,sBA5BA,qBACA,yBAWA,OAsBA,IAjCA,KACA,OAgCA,uBAKA,iCAGA,sIAEA,uCA6NA,EA1NA,oCASA,6CAiNA,EA1NA,WAIA,6CAsNA,IA9MA,gEAEA,cAkBA,YAGA,QADA,6CAwLA,EA7LA,6CA6LA,EA9KA,6CA8KA,EAnKA,uCAmKA,EA/JA,uCA+JA,EA5JA,uCA4JA,EAzJA,2CAyJA,EAtJA,2CAsJA,EAnJA,uCAmJA,EAhJA,uCAgJA,EA7IA,uCA6IA,EA1IA,2CA0IA,EAtIA,uCAsIA,EAjIA,uCAiIA,EAtHA,0EAuDA,cACA,qCAcA,4BACA,2CA+CA,GA7CA,2CA6CA,EAzCA,OAEA,UAGA,SAEA,kBAGA,sBACA,OAEA,qBACA,6JAIA,yBAEA,QAWA,UArBA,IAeA,wLAfA,iBAmBA,OACA,qBACA,MArBA,IAHA,AA0BA,IACA,2CAIA,oCA/BA,IAkCA,GA1DA,iCAGA,qBAHA,kCAKA,uCAqDA,GAtHA,MAWA,qBACA,OAFA,OAEA,eAZA,AAiBA,wHAIA,2CAiGA,EA/FA,2CA+FA,EArGA,AAQA,OAOA,UANA,2CA4FA,EAtFA,qBACA,2CAqFA,GArGA,EAiBA,oHAEA,2CAkFA,GA/EA,QAEA,qBACA,cADA,wDAxBA,YA8BA,2CAuEA,GAnEA,qDAuEA,oBACA,iDAEA,wBAIA,sBAPA,WAgBA,IARA,OAQA,OA2NA,4BAMA,EANA,4BAMA,EAJA,4BACA,aACA,6CAMA,UACA,OACA,cAEA,mCACA,cAEA,IACA",
   "sources" : [
      "runner.c",
      "stdlib.c",
      "../tokens/helper.c",
      "../parser.c",
      "../token.c"
   ]
}
```

**Comment by egberts** [comment]
One observation... file timestamping of `runner.wasm` got borked.

```bash
$ file *
README.md:       ASCII text
index.html:      HTML document text, ASCII text
release.sh:      Bourne-Again shell script text executable, ASCII text
runner.c:        c program text, ASCII text
runner.wasm:     , created: Fri Jan 22 21:09:21 2021, modified: Tue Apr  7 16:59:46 1970
runner.wasm.map: ASCII text, with very long lines, with no line terminators
runner.wast:     ASCII text, with very long lines
stdlib.c:        c program text, ASCII text
utils.js:        ASCII text
wasm.sh:         Bourne-Again shell script text executable, ASCII text
```

**Comment by egberts** [comment]
Attached is the result of `runner.wasm` (with TXT file extension added)
[runner.wasm.txt](https://github.com/samthor/prsr/files/3267842/runner.wasm.txt)

**Comment by samthor** [comment]
I'm glad you're interested in my weird C code 👍 

I suspect Emscripten is changing how it generates some of its metadata. I'm running 1.38.31, but I'll try upgrading today and let you know how it goes.

FWIW, I'm also realising that I don't really need Emscripten and I might switch to a pure Clang approach (aka @surma's [post](https://dassur.ma/things/c-to-webassembly/)).
